pfixtools
=========

pfixtools is a suite of tools aiming at complementing postfix, to make it even
more customizable, while keeping really high performance levels. This is in
particular why all the major Postfix Tools are written in plain C.

This suite contains at the time of the writing, two major tools.

link:/Fruneau/pfixtools/tree/master/pfix-srsd/pfix-srsd.asciidoc[+pfix-srsd+]::
    this daemon brings SRS to postfix using its
    link:http://www.postfix.org/tcp_table.5.html[tcp_table(5)] mechanism. It
    allows plugging +SRS+ into
    link:http://www.postfix.org/canonical.5.html[canonical(5)] or
    link:http://www.postfix.org/transport.5.html[transport(5)] rewrites quite easily.

link:/Fruneau/pfixtools/tree/master/postlicyd/postlicyd.asciidoc[+postlicyd+]::
    this is a postfix policy daemon. It includes greylisting, rbl lookups,
    counters, SMTP session tracking, in a way that allow very fine grained
    schemes. It's for example quite easy to reject a mail just at the
    `SMTP` `DATA` command using results from filtering done at the `RCPT TO`
    or even the `MAIL FROM` commands.
+
Its configuration file is described in
link:/Fruneau/pfixtools/tree/master/postlicyd/postlicyd.conf.asciidoc[postlicyd.conf].

Download
--------

The sources are availble from link:/Fruneau/pfixtools[github].

* link:/Fruneau/pfixtools/tarball/pfixtools-0.9[version 0.9] (September 22th, 2012)
* latest sources: link:/Fruneau/pfixtools/tarball/master[pfixtools snapshot]
* from git: `git clone https://github.com/Fruneau/pfixtools.git`

Previous versions (see [browser:ChangeLog]):

* https://github.com/Fruneau/pfixtools/tarball/pfixtools-0.7[version 0.8] (October 22th, 2009)
* https://github.com/Fruneau/pfixtools/tarball/pfixtools-0.7[version 0.7] (September 15th, 2009)
* https://github.com/Fruneau/pfixtools/tarball/pfixtools-0.6[version 0.6] (February 26th, 2009)
* https://github.com/Fruneau/pfixtools/tarball/pfixtools-0.5[version 0.5] (November 11th, 2008)
* https://github.com/Fruneau/pfixtools/tarball/pfixtools-0.4[version 0.4] (October 17th, 2008)

Installation
------------

Supported platforms
~~~~~~~~~~~~~~~~~~~

The pfixtools have been currently successfully compiled and installed on the following platorms:

* Linux: gentoo, debian etch, debian lenny, arch linux
* MacOS X 10.5 (Leopard), 10.6 (Snow Leopard)

Known bugs:

* dns lookup crashed on debian lenny due to a bug in the version of libunbound shipped in the distribution. A workaround is to manually install a more recent version of the library (known to work with libunbound 1.4).

Other platforms might work with some Makefile tuning if gcc is available.

Requirements
~~~~~~~~~~~~

The following libraries are required to build and run the pfixtools:

* http://software.schmorp.de/pkg/libev.html[libev]
* http://www.libsrs2.org/[libsrs2]
* http://tokyocabinet.sourceforge.net/index.html[tokyocabinet] _(`postlicyd` only)_
* http://unbound.net/index.html[libunbound] _(`postlicyd` only)_
* http://www.pcre.org/[libpcre] _(`postlicyd` only)_

The following are build-time dependencies:

* gcc: 4.0 or later
* pkg-config _(`postlicyd` only)_
* gperf _(`postlicyd` only)_
* libpcre3 _(`postlicyd` only)_
* xmlto, docbook-xsl and asciidoc to build the documentation (this is only a stub of documentation)

Compilation
~~~~~~~~~~~

To install the pfixtools, just run `make all doc` and `sudo make install`.

If you don't want to compile all the tools, you can run `make toolname` and `sudo make install-toolname`. You can also specify the installation prefix and a sandbox path `sudo make install prefix=/my/prefix DESTDIR=/my/sandbox`.

Legal
-----

These programs are free softwares distributed AS IS. Please refer to the link:LICENSE[LICENSE file] for details.

Authors:

* link:/MadCoder[Pierre Habouzit] (c) 2006-2009: common library, pfix-srsd
* link:/Fruneau[Florent Bruneau] (c) 2008-2010: common library, postlicyd

Contributors:

* link:/aaugustin[Aymeric Augustin] (c) 2008: postgrey to postlicyd tool
* link:/ebzao[Nicolas Aupetit] (c) 2008: debian packaging
* http://vincent.m4z.org/[Vincent Zanotti] (c) 2009: build fixes
* Michael Scherer (c) 2009: build fixes
* https://github.com/driskell[Jason Woods] 2013: socketmap protocol / socketfiles and others
